const FETCH_HEROES_REQUEST = "FETCH_HEROES_REQUEST";
const FETCH_HEROES_SUCCESS = "FETCH_HEROES_SUCCESS";
const CLEAR_HEROES = "CLEAR_HEROES";

export { FETCH_HEROES_REQUEST, FETCH_HEROES_SUCCESS, CLEAR_HEROES };
