const FETCH_TEAMS_REQUEST = "FETCH_TEAMS_REQUEST";
const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";

export { FETCH_TEAMS_REQUEST, FETCH_TEAMS_SUCCESS, DELETE_TEAM_SUCCESS };
