const FETCH_HERO_REQUEST = "FETCH_HEROES_REQUEST";
const FETCH_HERO_SUCCESS = "FETCH_HEROES_SUCCESS";
const CLEAR_HERO = "CLEAR_HEROES";

export { FETCH_HERO_REQUEST, FETCH_HERO_SUCCESS, CLEAR_HERO };
