const TEAMS_FILTERS = {
  HIGHEST_SCORE: "Mayor puntaje arriba",
  LOWEST_SCORE: "Menor puntaje arriba",
};

const HEROES_PER_TEAM = 6;
const GOOD_HEROES_PER_TEAM = HEROES_PER_TEAM / 2;
const BAD_HEROES_PER_TEAM = HEROES_PER_TEAM / 2;

const FETCHED_HEROES_LIMIT = 12;

export {
  TEAMS_FILTERS,
  HEROES_PER_TEAM,
  GOOD_HEROES_PER_TEAM,
  BAD_HEROES_PER_TEAM,
  FETCHED_HEROES_LIMIT,
};
