const FETCH_TEAM_REQUEST = "FETCH_TEAM_REQUEST";
const FETCH_TEAM_SUCCESS = "FETCH_TEAM_SUCCESS";
const SAVE_TEAM_REQUEST = "SAVE_TEAM_REQUEST";
const SAVE_TEAM_SUCCESS = "SAVE_TEAM_SUCCESS";
const CLEAR_TEAM = "CLEAR_TEAM";

export {
  FETCH_TEAM_REQUEST,
  FETCH_TEAM_SUCCESS,
  SAVE_TEAM_REQUEST,
  SAVE_TEAM_SUCCESS,
  CLEAR_TEAM,
};
